# Generated by Django 5.1.7 on 2025-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
