# Generated by Django 5.1.7 on 2025-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitetext_content1_alter_sitetext_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usser',
            name='up_arrow',
            field=models.ImageField(blank=True, null=True, upload_to='up_arrow/'),
        ),
    ]
