# Generated by Django 5.1.7 on 2025-03-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usser_up_arrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='usser',
            name='team1',
            field=models.ImageField(blank=True, null=True, upload_to='team1/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='team2',
            field=models.ImageField(blank=True, null=True, upload_to='team2/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='team3',
            field=models.ImageField(blank=True, null=True, upload_to='team3/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='team4',
            field=models.ImageField(blank=True, null=True, upload_to='team4/'),
        ),
    ]
