# Generated by Django 5.1.7 on 2025-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usser_team1_usser_team2_usser_team3_usser_team4'),
    ]

    operations = [
        migrations.AddField(
            model_name='usser',
            name='testimonial1',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial1/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='testimonial2',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial2/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='testimonial3',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial3/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='testimonial4',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial4/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='testimonial5',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial5/'),
        ),
        migrations.AddField(
            model_name='usser',
            name='testimonial6',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial6/'),
        ),
    ]
