# Generated by Django 5.1.7 on 2025-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usser_testimonial1_usser_testimonial2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
