# Generated by Django 5.1.7 on 2025-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitetext_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
