# Generated by Django 5.1.7 on 2025-03-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitetext_content3'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='serv1_div1',
            field=models.CharField(default='Environment and competition', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv1_div2',
            field=models.CharField(default='Designing the marketing plan', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv1_price',
            field=models.CharField(default='$199', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv1_text',
            field=models.CharField(default='Perfect for fresh ideas or young startups, this package will help get the business off the ground', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv1_title',
            field=models.CharField(default='Off The Ground Off The Ground', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv2_div1',
            field=models.CharField(default='Business strategy planning', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv2_div2',
            field=models.CharField(default='Taking the planned actions', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv2_price',
            field=models.CharField(default='$299', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv2_text',
            field=models.CharField(default='Use this service pack to give your company the necessary impulse to become an industry leader', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv2_title',
            field=models.CharField(default='Accelerated Growth', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv3_div1',
            field=models.CharField(default='Maintaining the leader status', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv3_div2',
            field=models.CharField(default='Acquisitions the right way', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv3_price',
            field=models.CharField(default='$299', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv3_text',
            field=models.CharField(default='You already are a reference point in your industry now you need to learn about acquisitions', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='serv3_title',
            field=models.CharField(default='Market Domination', max_length=255),
        ),
    ]
