# Generated by Django 5.1.7 on 2025-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sitetext_test1_text_alter_sitetext_test2_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='team1_name',
            field=models.CharField(default='John Whitelong', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team1_title',
            field=models.CharField(default='General Manager', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team2_name',
            field=models.CharField(default='Veronique Smith', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team2_title',
            field=models.CharField(default='Business Developer', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team3_name',
            field=models.CharField(default='Chris Zimerman', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team3_title',
            field=models.CharField(default='Online Marketer', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team4_name',
            field=models.CharField(default='Mary Villalonga', max_length=255),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='team4_title',
            field=models.CharField(default='Community Manager', max_length=255),
        ),
    ]
