# Generated by Django 5.1.7 on 2025-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitetext_team1_name_sitetext_team1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='email',
            field=models.EmailField(default='mailto:office@aria.com', max_length=150),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='phone_num1',
            field=models.CharField(default='+81 720 22 126', max_length=111),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='phone_num2',
            field=models.CharField(default='+81 720 22 128', max_length=111),
        ),
    ]
