# Generated by Django 5.1.7 on 2025-03-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_sitetext_email_sitetext_phone_num1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='address',
            field=models.CharField(default='22nd Innovative Street, San Francisco, CA 94043, US', max_length=255),
        ),
    ]
