# Generated by Django 5.1.7 on 2025-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sitetext_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetext',
            name='num1',
            field=models.IntegerField(default=231),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='num2',
            field=models.IntegerField(default=121),
        ),
        migrations.AddField(
            model_name='sitetext',
            name='num3',
            field=models.IntegerField(default=159),
        ),
    ]
