# Generated by Django 5.1.7 on 2025-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sitetext_num1_sitetext_num2_sitetext_num3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('interest', models.CharField(max_length=50)),
                ('agreed_to_terms', models.BooleanField(default=False)),
            ],
        ),
    ]
